# -*- coding: utf-8 -*-
"""COVID-19-Tweets-Sentiment-Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mBKMiPobHdOVLAGX8zx7UbAkh0EX3Mrn
"""

!pip install transformers datasets sentencepiece nltk pandas

from huggingface_hub import login

login()

import pandas as pd

df = pd.read_csv("/content/Corona_NLP_test.csv")  # change filename to your file
df.head()

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

def clean_text(text):
    encoded = tokenizer.encode(text, add_special_tokens=False)
    return tokenizer.decode(encoded)

df["clean_text_hf"] = df["OriginalTweet"].astype(str).apply(clean_text)
df.head()

import nltk
nltk.download("stopwords")
nltk.download("wordnet")
nltk.download("punkt")
nltk.download("punkt_tab")

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import string

stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

def advanced_clean(text):
    text = text.lower()
    words = nltk.word_tokenize(text)
    words = [w for w in words if w not in stop_words and w not in string.punctuation]
    words = [lemmatizer.lemmatize(w) for w in words]
    return " ".join(words)

df["clean_text_final"] = df["clean_text_hf"].apply(advanced_clean)
df.head()

"""# ***Sentiment Analysis Using Hugging Face***"""

!pip install transformers torch

from transformers import pipeline

sentiment_model = pipeline("sentiment-analysis")

def get_sentiment(text):
    result = sentiment_model(text[:512])[0]
    return result['label'], result['score']

df['sentiment_label'], df['sentiment_score'] = zip(*df['clean_text_final'].astype(str).apply(get_sentiment))
df.head()

df['sentiment_value'] = df['sentiment_label'].apply(lambda x: 1 if x == 'POSITIVE' else 0)

print(df['sentiment_label'].value_counts())

print(df['sentiment_value'].mean())

df.to_csv("sentiment_output.csv", index=False)

from google.colab import files
files.download("sentiment_output.csv")